service: lambda-name # lambda name

useDotenv: true   #.env use

plugins:
  - serverless-offline

provider:
  name: aws  
  runtime: nodejs18.x  #version of nodejs
  region: us-east-1 #region to deploy

functions:
  name:  #function name
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}' 
